export const LOGIN_JOBSEEKER = "LOGIN_JOBSEEKER";
export const AUTH_JOBSEEKER = "AUTH_JOBSEEKER";
export const REGISTER_JOBSEEKER = "REGISTER_JOBSEEKER";
export const LOGOUT_JOBSEEKER = "LOGOUT_JOBSEEKER";
export const GOOGLE_LOGIN_JOBSEEKER = "GOOGLE_LOGIN_JOBSEEKER";
